env: local #dev,prod,local
http_server:
  address: 0.0.0.0:8080
  read_timeout: 3s
  write_timeout: 5s
  read_header_timeout: 1s
  idle_timeout: 60s
  jwt_expire: 1h
db_config:
  host: ${DB_HOST}
  port: 5432
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  max_connections: 10
  min_connections: 2
  max_connection_life: 60m
  max_connection_idle_time: 30m

