env: local #dev,prod,local
http_server:
  address: 0.0.0.0:8080
  read_timeout: 3s
  write_timeout: 5s
  read_header_timeout: 1s
  idle_timeout: 60s
db_config:
  host: ${DB_HOST}
  port: 5432
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
